// File generated by FlutterFire CLI and modified to secure API keys.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: SyncScaleFirebaseOptions.current,
/// );
/// ```
class SyncScaleFirebaseOptions {
  static FirebaseOptions get current {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'SyncScaleFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'SyncScaleFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_API_KEY_WEB')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_API_KEY_WEB') : ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_WEB').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_APP_ID_WEB')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_APP_ID_WEB') : ''),
        messagingSenderId: '66964728618',
        projectId: 'sync-scale',
        authDomain: 'sync-scale.firebaseapp.com',
        storageBucket: 'sync-scale.firebasestorage.app',
        measurementId: 'G-0XMGMQSVGL',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_API_KEY_ANDROID')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_API_KEY_ANDROID') : ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_ANDROID').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_APP_ID_ANDROID')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_APP_ID_ANDROID') : ''),
        messagingSenderId: '66964728618',
        projectId: 'sync-scale',
        storageBucket: 'sync-scale.firebasestorage.app',
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_API_KEY_IOS')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_API_KEY_IOS') : ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_IOS').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_APP_ID_IOS')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_APP_ID_IOS') : ''),
        messagingSenderId: '66964728618',
        projectId: 'sync-scale',
        storageBucket: 'sync-scale.firebasestorage.app',
        androidClientId: '66964728618-1c375ckrvho6mklk072u871hd4n4t3ha.apps.googleusercontent.com',
        iosClientId: '66964728618-tcrq9t43b44cil433f0a1gtsesk53ogi.apps.googleusercontent.com',
        iosBundleId: 'com.example.mobileApp',
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_MACOS').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_API_KEY_MACOS')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_API_KEY_MACOS') : ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_MACOS').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_APP_ID_MACOS')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_APP_ID_MACOS') : ''),
        messagingSenderId: '66964728618',
        projectId: 'sync-scale',
        storageBucket: 'sync-scale.firebasestorage.app',
        androidClientId: '66964728618-1c375ckrvho6mklk072u871hd4n4t3ha.apps.googleusercontent.com',
        iosClientId: '66964728618-tcrq9t43b44cil433f0a1gtsesk53ogi.apps.googleusercontent.com',
        iosBundleId: 'com.example.mobileApp',
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WINDOWS').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_API_KEY_WINDOWS')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_API_KEY_WINDOWS') : ''),
        appId: const String.fromEnvironment('FIREBASE_APP_ID_WINDOWS').isNotEmpty
            ? const String.fromEnvironment('FIREBASE_APP_ID_WINDOWS')
            : (dotenv.isInitialized ? dotenv.get('FIREBASE_APP_ID_WINDOWS') : ''),
        messagingSenderId: '66964728618',
        projectId: 'sync-scale',
        authDomain: 'sync-scale.firebaseapp.com',
        storageBucket: 'sync-scale.firebasestorage.app',
        measurementId: 'G-JH98CQ0PCT',
      );
}
