// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BUa4Qe3otPLSWP-pDuPUZsmVMhICqmc',
    appId: '1:66964728618:web:47df49602aab9b966dcc53',
    messagingSenderId: '66964728618',
    projectId: 'sync-scale',
    authDomain: 'sync-scale.firebaseapp.com',
    storageBucket: 'sync-scale.firebasestorage.app',
    measurementId: 'G-0XMGMQSVGL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI_hbDu1-sExr4UkWZldPHTQ7wQYYRgvI',
    appId: '1:66964728618:android:9d3e512772db66b36dcc53',
    messagingSenderId: '66964728618',
    projectId: 'sync-scale',
    storageBucket: 'sync-scale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKtN25bp0K5KBgQpUUVkYgLRmOoXwdA8',
    appId: '1:66964728618:ios:91df6d1c632868186dcc53',
    messagingSenderId: '66964728618',
    projectId: 'sync-scale',
    storageBucket: 'sync-scale.firebasestorage.app',
    androidClientId: '66964728618-1c375ckrvho6mklk072u871hd4n4t3ha.apps.googleusercontent.com',
    iosClientId: '66964728618-tcrq9t43b44cil433f0a1gtsesk53ogi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgKtN25bp0K5KBgQpUUVkYgLRmOoXwdA8',
    appId: '1:66964728618:ios:91df6d1c632868186dcc53',
    messagingSenderId: '66964728618',
    projectId: 'sync-scale',
    storageBucket: 'sync-scale.firebasestorage.app',
    androidClientId: '66964728618-1c375ckrvho6mklk072u871hd4n4t3ha.apps.googleusercontent.com',
    iosClientId: '66964728618-tcrq9t43b44cil433f0a1gtsesk53ogi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7BUa4Qe3otPLSWP-pDuPUZsmVMhICqmc',
    appId: '1:66964728618:web:906da7013f3e97a26dcc53',
    messagingSenderId: '66964728618',
    projectId: 'sync-scale',
    authDomain: 'sync-scale.firebaseapp.com',
    storageBucket: 'sync-scale.firebasestorage.app',
    measurementId: 'G-JH98CQ0PCT',
  );
}
